### ISSUE TITLE
Nested formData object outputs unreadable email body

### ISSUE THREAD

**Issue by treighmawaka** [excl-networks/strapi-plugin-ezforms#10]
Consider the following formData object:
```json
{
  "contact": {
    "email": "user@domain.com",
    "phone": "(555) 555-5555",
    "lastname": "Milou",
    "firstname": "Tintin"
  },
  "services": [
    {
      "Assurances": [
        "Dommages"
      ]
    },
    {
      "Placement": [
        "Oui"
      ]
    },
    {
      "Hypothèque": [
        "Refinancement"
      ]
    }
  ]
}
```

When the form is submitted, the data output in the notification email  shows a string representation of the object instead of printing the nested key/value pairs i.e.
```
New Conact Form Submission
contact: [object Object]
services: [object Object], [object Object], [object Object]
```

This is likely due to the fact that the [email notification provider service](https://github.com/excl-networks/strapi-plugin-ezforms/blob/master/server/services/notification-providers/email.js#L7) is expecting a flat formData object.
A quick workaround could be to stringify nested keys when constructing the message output.
```js
for(let key in data)
  message += `${key}: ${JSON.stringify(data[key])}\n`;` // 👈
}
```
```js
// instead of 👇
for(let key in data){
  message += `${key}: ${data[key]}\n`
}
```

**Comment by Cpaczek** [comment]
Fixed in https://github.com/excl-networks/strapi-plugin-ezforms/pull/13

Non complex data structures will still format as normal however any object types will use JSON.stringify(data, null, 2) to make it look a little pretty. Feel free to modify the formatData function if you want to make it look better.

**Comment by treighmawaka** [comment]
Well done. Thank!
