### ISSUE TITLE
Invalid captcha still send email

### ISSUE THREAD

**Issue by arixwap** [excl-networks/strapi-plugin-ezforms#15]
Hello, I found some issue with your plugin while I using Google Recaptcha.
Email notifications are still sent even though the score is **-1**.

But I already fixed it in here in my PR (https://github.com/excl-networks/strapi-plugin-ezforms/pull/14)

**Comment by Cpaczek** [comment]
Hi,
I see the issue, it was caused by not returning on the controller after an invalid captcha. I've fixed this in my own commit as well as add eslint. Thank you for finding this. Please update to .10 and let me know if your still having issues

**Comment by arixwap** [comment]
Nice, thanks!

**Comment by edolix** [comment]
Hey @cpaczek - i'm using the latest version `0.1.7` and i've got few email with score < `minimumScore`.

In `plugins.ts` i have:

```
      captchaProvider: {
        name: env('GOOGLE_RECAPTCHA_KEY') ? 'recaptcha' : 'none',
        config: {
          secretKey: env('GOOGLE_RECAPTCHA_KEY'),
          minimumScore: 0.7,
        },
      }
```

`GOOGLE_RECAPTCHA_KEY` is correctly set but the email from this form submission was delivered (score 0.1).

![Image](https://github.com/user-attachments/assets/2a39abad-9775-4c0c-a053-c09c4228f52f)

Thanks!

**Comment by edolix** [comment]
Looks like the code is checking `score` and not `minimumScore` as [described in the docs here](https://ezforms.excl.dev/captcha-providers.html#captcha-providers)

https://github.com/excl-networks/strapi-plugin-ezforms/blob/ef81739314e85255ee16f8134cc1e7df02fdbbcf/server/services/captcha-providers/recaptcha.js#L38
