### ISSUE TITLE
How to associate a submissions to a form

### ISSUE THREAD

**Issue by mariojsnunes** [excl-networks/strapi-plugin-ezforms#17]
I have multiple forms on my website, as I understand, they are all submitted to the same "Form Submissions".
Is there a way to provide a title/identifier to the form submission?

Something like this:
![image](https://user-images.githubusercontent.com/8073622/189053666-65a44d0f-6c62-48ac-951c-691cbe0e2a1f.png)

**Comment by Cpaczek** [comment]
Yes this is something we could implement, feel free to make a PR or I will get to it eventually.

**Comment by Zaya1101** [comment]
Made a PR [here](https://github.com/excl-networks/strapi-plugin-ezforms/pull/19)

**Comment by Cpaczek** [comment]
Merged and published
