### ISSUE TITLE
I'm getting this error: TypeError: Cannot read property 'score' of undefined

### ISSUE THREAD

**Issue by ychasse01** [excl-networks/strapi-plugin-ezforms#2]
Content of my ./config/plugins.js

`module.exports = ({ env }) => ({
  "ezforms": {
    config:{
      captchaProvider: {
        name: 'none'
      },
      notificationProviders: [ ]
    }
  }
})`

The error is happening on line 
`let parsedScore = verification.score || -1`
which is odd because it really looks perfectly fine to me...

I'm running in a container: node:14-alpine. Any ideas would be appreciated.

**Comment by ychasse01** [comment]
I ended up fixing the issue by changing the test.
`let parsedScore = verification.score || -1`
to 
`let parsedScore = verification ? ( verification.score || -1  ) : -1`

I hope this helps

**Comment by Cpaczek** [comment]
@ychasse01 Fixed in latest build 0.0.7

See this commit: https://github.com/excl-networks/strapi-plugin-ezforms/commit/567b2dd57e8c8bb31ac99ff25456447b7d3a58a2

**Comment by ychasse01** [comment]
Awesome thanks, much better solution! I'm not the strongest developer lollll!
