### ISSUE TITLE
Unsupported engine error

### ISSUE THREAD

**Issue by nicelion** [excl-networks/strapi-plugin-ezforms#20]
When installing the extension, the following is outputted:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'strapi-plugin-ezforms@0.1.2',
npm WARN EBADENGINE   required: { node: '>=12.x. <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.15.0', npm: '8.5.5' }
npm WARN EBADENGINE }
```

I am assuming this might have to do with the version of node I am using; however, it seems that the current version of node is compatible with the requirements that are specified in the output. Maybe I am reading it wrong.

**Comment by Damien-Ar** [comment]
I had the same issue, it might come from the missing x in the `12.x.` version in the package.json (should be `12.x.x`)

**Comment by Cpaczek** [comment]
I'll try and reproduce later today hopefully it's an easy typo fix, if you've confirmed the additional x works feel free to open a PR and assuming tests pass I can deploy a new version from my phone.

**Comment by Cpaczek** [comment]
@nicelion I update the package json and redeployed to NPM please try again with v0.1.3

**Comment by Cpaczek** [comment]
Closing as there is no update. If this is still an issue please let me know
