### ISSUE TITLE
Is it possible to create a draft of a certain content-type upon submission?

### ISSUE THREAD

**Issue by sha237gh** [excl-networks/strapi-plugin-ezforms#21]
Hi,

we are looking into ezforms for our project. While it works great for creating the `Form Submissions` content type we are wondering if it would be possible somehow to put the data into our own custom content-type. As for the docs, they are only listing captcha validation and notifications for customization. Our desired functionality however would be to create a draft of a content-type called "Project".

Hope this makes sense, thanks in advance!

**Comment by Cpaczek** [comment]
You would hook into the afterCreate() lifecycle function of the form submissions type.

In your bootstrap function you would have some code like this
https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#declarative-and-programmatic-usage
```js
// ./src/index.js
module.exports = {
  register() {
    // some sync code
  },
  bootstrap() {
   strapi.db.lifecycles.subscribe({
    models: ['submission'], // optional;

     afterCreate(event) {
      // Use entity service API to add a draft to 'project'
     // this code will run whenever a submission is created.
  },
});
  },
  destroy() {
    // some sync code
  }
};

```

You also could create a custom controller which would give you a bit more control. This plugin is made so you can use bits and pieces of it's logic so you don't need to rewrite it.

You can view the docs here: https://ezforms.excl.dev/advanced/custom-controller.html

For example, if you want to send a notification text you can just use this code
```js
let config = {
    accountSid: 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    authToken: 'your_auth_token',
    from: '+12345678901',
}
let data = {
    name: 'John Doe',
    email: 'test@gmail.com'
}

strapi.plugin('ezforms').service('twilio').send(config, data)
```

**Comment by sha237gh** [comment]
Works perfectly with the bootstrap function, thanks a lot!
