### ISSUE TITLE
Custom email template

### ISSUE THREAD

**Issue by BenCherif** [excl-networks/strapi-plugin-ezforms#26]
is there a way to select a strapi template and set it to ezforms formData?

**Comment by cpaczek** [comment]
The easiest way to do this would be to create a custom notification provider: https://ezforms.excl.dev/advanced/custom-notification-provider.html

You can use this as a guide: https://github.com/excl-networks/strapi-plugin-ezforms/blob/master/server/services/notification-providers/email.js

If you do make a custom notification provider I would be happy to add it to the core functionality of the plugin. Feel free to make a PR.

**Comment by BenCherif** [comment]
Thanks bro for your helpful reply
