### ISSUE TITLE
Permission denied for Public user

### ISSUE THREAD

**Issue by Mathys-Rituper** [excl-networks/strapi-plugin-ezforms#3]
Hi,

When trying to submit the form with the role public, i get the following response : 

```
XHRPOSThttp://localhost:1337/api/ezforms/submit
[HTTP/1.1 500 Internal Server Error 13ms]	
data	null
error	Object { status: 500, name: "InternalServerError", message: "Internal Server Error" }
status	500
name	"InternalServerError"
message	"Internal Server Error"
```

The server logs the following : 
`[2022-02-14 11:59:06.099] error: Forbidden access
ForbiddenError: Forbidden access`

However there does not seem to be any way to grant the Public user the needed permissions since the plugin's tables do not show up on the usual Permissions tab.

How can I fix that ?

Additional information : 
Plugin version : 4.0.0
Strapi version : 4.0.7
Node version : 14.17.2
Npm version : 6.14.13

**Comment by Cpaczek** [comment]
The submit controller function should be available within user permissions as seen here:
![image](https://user-images.githubusercontent.com/25715982/154024138-be305a3a-6596-4e77-b0bb-8f79762e4357.png)
Is this checked for your public role? http://localhost:1337/admin/settings/users-permissions/roles

**Comment by Mathys-Rituper** [comment]
> The submit controller function should be available within user permissions as seen here: ![image](https://user-images.githubusercontent.com/25715982/154024138-be305a3a-6596-4e77-b0bb-8f79762e4357.png) Is this checked for your public role? http://localhost:1337/admin/settings/users-permissions/roles

It didn't show up when I wrote the post but I just updated my project and it has appeared and seems to be working now. Thanks !
