### ISSUE TITLE
Error 500 on submit

### ISSUE THREAD

**Issue by etomarat** [excl-networks/strapi-plugin-ezforms#30]
Hello! ezforms plugin has stopped working. When front send request:
`POST https://admin.ensy.tech/api/ezforms/submit/`
```
{"token":"HFOWw5KhUdfxRCDmUMF0YdFgBjMiNeKDJoNDFIZhtYSwtWVSxKXUdOaDsgITcQMHoHVQ9nXR87XR9COSEnHE1zbRh5TUZfW2sPCEswQU40CGd5RlsqRzh_QWZNZx8TEGVPNW0zOFUIIG1eFR1hPEo8CVUYBlVKYwx_aWU","formName":"Some name","formData":{"name":"test","email":"my@email.com","phone":"some string","message":"some string"}}
```
We get 500 error:
```
{
    "data": null,
    "error": {
        "status": 500,
        "name": "InternalServerError",
        "message": "There was an error, check Strapi logs for more details. Unable to verify captcha",
        "details": {}
    }
}
```
In strapi logs i only have:
```
[2023-07-07 12:47:18.905] error: recaptcha_verify
[2023-07-07 12:47:18.906] error: undefined
```
What could be the issue? Thanks!

**Comment by cpaczek** [comment]
This is most likely because you don't  have your secret key set in your config

You can view config here: https://ezforms.excl.dev/captcha-providers.html

**Comment by etomarat** [comment]
> This is most likely because you don't have your secret key set in your config
> 
> You can view config here: https://ezforms.excl.dev/captcha-providers.html
No, I have secret key. At first it worked, then it stopped

<img width="511" alt="image" src="https://github.com/excl-networks/strapi-plugin-ezforms/assets/710389/b8437523-b979-497a-af0a-c81ca54da81b">

**Comment by etomarat** [comment]
> Are you using Recaptcha v3?

yes

**Comment by kamit-transient** [comment]
I am also getting exactly same error with Recaptcha V3.

@etomarat  did you find any solution?

**Comment by etomarat** [comment]
@kamit-transient 
As far as I know, the problem was solved by disabling some nginx security settings. Unfortunately, I left the project and alas, I do not know the details

**Comment by cpaczek** [comment]
Going to close for now as I can't reproduce, if someone could reply with steps to reproduce I would be happy to take a look.
