### ISSUE TITLE
Strapi endpoint returns 404

### ISSUE THREAD

**Issue by Digiversecz** [excl-networks/strapi-plugin-ezforms#39]
Submit endpoint returns error 404 with or without API in URL.

Strapi: v4.20.2
Node: v18.18.2
strapi-plugin-ezforms: "^0.1.7",

http://localhost:1339/api/ezforms/submissions
http://localhost:1339/ezforms/submissions

![image](https://github.com/excl-networks/strapi-plugin-ezforms/assets/94712794/21191478-551d-4a6e-8cfa-b84a4b19a9d1)

**Comment by cpaczek** [comment]
What does your request look like. Make sure you are doing a POST request

**Comment by Digiversecz** [comment]
Thanks for quick response. When we use POST we get error 500:

const response = await fetch(“http://localhost:1339/api/ezforms/submit”, {
      method: “POST”,
      headers: {
        “Content-Type”: “application/json”,
      },
      body: JSON.stringify({
        token: “6LdPHXspAAAAAPyWKNbjVr4Jvgia0bnNVIIxd_GR”,
        formName: formName,
        formData: formData,
      }),
    });

![image](https://github.com/excl-networks/strapi-plugin-ezforms/assets/94712794/e98b713f-7906-410e-a79d-56f2ed9c187c)

**Comment by cpaczek** [comment]
Can you send the strapi logs when you send that request, there should be some logging that will help me debug.

**Comment by Digiversecz** [comment]
Wrong integration of reCaptcha on our side. Sorry of inconviniences.
