### ISSUE TITLE
GraphQL forbidden access

### ISSUE THREAD

**Issue by salahaz** [excl-networks/strapi-plugin-ezforms#9]
Hello,

When I try to create new form submissions using the graphql mutation. I receive "Forbidden Access" message. It works using REST API, not GraphQL though. 

Does ezforms supports graphql ?
<img width="1385" alt="Screen Shot 2022-06-28 at 12 18 03 PM" src="https://user-images.githubusercontent.com/41476094/176166329-b10934e4-4c9b-4d2e-9e58-7a47d9a135d7.png">

**Comment by Cpaczek** [comment]
Did you allow permission for the public role to access it? https://github.com/excl-networks/strapi-plugin-ezforms#permission-setup

**Comment by Cpaczek** [comment]
Is this still an issue? If so please feel free to reopen :)

**Comment by tcherokee** [comment]
@salahaz Did you manage to get this working? I am running into the same error and I have enabled permission for the public role.

**Comment by VincentDugard** [comment]
Same problem here, I've setup permissions. anonymous REST call works but graphql return Forbidden access
